In [ ]:
from google.colab import files
uploaded = files.upload()

In [3]:
import pandas as pd;
clean_invoice=pd.read_csv('sample_data/clean-invoice.csv',index_col='invoice_id');
clean_invoice.head()

,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
invoice_id,,,,,,,,
1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,1.98
2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,Unknown,Norway,0171,3.96
3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,Unknown,Belgium,1000,5.94
4,14,2021-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
5,23,2021-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

In [4]:
# clean_invoice.drop(['clean_billing_state','clean_postal_code'],axis=1,inplace=True)
clean_invoice.head()

,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
invoice_id,,,,,,,,
1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,1.98
2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,Unknown,Norway,0171,3.96
3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,Unknown,Belgium,1000,5.94
4,14,2021-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
5,23,2021-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

In [5]:
# clean_invoice['billing_state'].fillna('Unknown', inplace=True)
# clean_invoice['billing_postal_code'].fillna('Unknown', inplace=True)
clean_invoice.head()

,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
invoice_id,,,,,,,,
1,2,2021-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,1.98
2,4,2021-01-02 00:00:00,Ullevålsveien 14,Oslo,Unknown,Norway,0171,3.96
3,8,2021-01-03 00:00:00,Grétrystraat 63,Brussels,Unknown,Belgium,1000,5.94
4,14,2021-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
5,23,2021-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86

In [31]:
clean_invoice.isna().sum()

customer_id            0
invoice_date           0
billing_address        0
billing_city           0
billing_state          0
billing_country        0
billing_postal_code    0
total                  0
dtype: int64

In [23]:
clean_invoice.to_csv('sample_data/clean-invoice.csv')

In [6]:
clean_customer=pd.read_csv('sample_data/clean-customer.csv',index_col='customer_id');
clean_customer.head()

,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
customer_id,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,Unknown,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,+49 0711 2842222,Unknown,leonekohler@surfeu.de,5
3,François,Tremblay,Unknown,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,Unknown,ftremblay@gmail.com,3
4,Bjørn,Hansen,Unknown,Ullevålsveien 14,Oslo,Unknown,Norway,0171,+47 22 44 22 22,Unknown,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,Unknown,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [30]:
# cleaning the customer dataset
# clean_customer.drop(['clean_state','postal_code.1','clean_company','clean_phone','clean_fax'],axis=1,inplace=True)
# clean_customer['company'].fillna('Unknown', inplace=True)
# clean_customer['postal_code'].fillna('Unknown', inplace=True)
# clean_customer['phone'].fillna('Unknown', inplace=True)
# clean_customer['state'].fillna('Unknown', inplace=True)
# clean_customer['fax'].fillna('Unknown', inplace=True)

clean_customer.head()

,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
customer_id,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,Unknown,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,+49 0711 2842222,Unknown,leonekohler@surfeu.de,5
3,François,Tremblay,Unknown,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,Unknown,ftremblay@gmail.com,3
4,Bjørn,Hansen,Unknown,Ullevålsveien 14,Oslo,Unknown,Norway,0171,+47 22 44 22 22,Unknown,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,Unknown,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [29]:
clean_customer.isna().sum()

first_name        0
last_name         0
company           0
address           0
city              0
state             0
country           0
postal_code       0
phone             0
fax               0
email             0
support_rep_id    0
dtype: int64

In [78]:
# clean_invoice.to_csv('sample_data/clean-invoice.csv')
clean_customer.to_csv('sample_data/clean-customer.csv')

In [71]:
# clean_invoice.info()
clean_customer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 1 to 59
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   first_name      59 non-null     object
 1   last_name       59 non-null     object
 2   company         59 non-null     object
 3   address         59 non-null     object
 4   city            59 non-null     object
 5   state           59 non-null     object
 6   country         59 non-null     object
 7   postal_code     59 non-null     object
 8   phone           59 non-null     object
 9   fax             59 non-null     object
 10  email           59 non-null     object
 11  support_rep_id  59 non-null     int64
dtypes: int64(1), object(11)
memory usage: 6.0+ KB

In [70]:
# print(clean_invoice.isna().sum())
print(clean_customer.isna().sum())

first_name        0
last_name         0
company           0
address           0
city              0
state             0
country           0
postal_code       0
phone             0
fax               0
email             0
support_rep_id    0
dtype: int64

In [7]:
clean_customer.head()

,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
customer_id,,,,,,,,,,,,
1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
2,Leonie,Köhler,Unknown,Theodor-Heuss-Straße 34,Stuttgart,Unknown,Germany,70174,+49 0711 2842222,Unknown,leonekohler@surfeu.de,5
3,François,Tremblay,Unknown,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,Unknown,ftremblay@gmail.com,3
4,Bjørn,Hansen,Unknown,Ullevålsveien 14,Oslo,Unknown,Norway,0171,+47 22 44 22 22,Unknown,bjorn.hansen@yahoo.no,4
5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,Unknown,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [8]:
# clean employee dataset
clean_employee=pd.read_csv('sample_data/clean-employee.csv',index_col='employee_id');
clean_employee.head()

,last_name,first_name,title,reports_to,birth_date,hire_date,address,city,state,country,postal_code,phone,fax,email
employee_id,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,0.0,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [9]:
# clean_employee.drop(columns=['clean_reports_to'], axis=1,inplace=True)
clean_employee.head()

,last_name,first_name,title,reports_to,birth_date,hire_date,address,city,state,country,postal_code,phone,fax,email
employee_id,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,0.0,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [39]:
clean_employee.to_csv('sample_data/clean-employee.csv')

In [40]:
# clean_employee.fillna(0, inplace=True)
clean_employee.head()

,last_name,first_name,title,reports_to,birth_date,hire_date,address,city,state,country,postal_code,phone,fax,email
employee_id,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,0.0,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [53]:
print(clean_employee.isna().sum())

last_name           0
first_name          0
title               0
reports_to          0
birth_date          0
hire_date           0
address             0
city                0
state               0
country             0
postal_code         0
phone               0
fax                 0
email               0
clean_reports_to    0
dtype: int64

In [57]:
clean_employee.to_csv('sample_data/clean-employee.csv')

In [10]:
# Clean track dataset
clean_track=pd.read_csv('sample_data/clean-track.csv',index_col='track_id');
clean_track.head()

,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
track_id,,,,,,,,
1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [45]:
# clean_track.drop(columns=['clean_composer'],inplace=True)
clean_track.head()

,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
track_id,,,,,,,,
1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [46]:
clean_track.head()

,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
track_id,,,,,,,,
1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [93]:
clean_track['composer'].fillna('Unknown', inplace=True)
clean_track.head()

,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
track_id,,,,,,,,
1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
2,Balls to the Wall,2,2,1,"U. Dirkschneider, W. Hoffmann, H. Frank, P. Ba...",342562,5510424,0.99
3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99

In [94]:
clean_track.isna().sum()

name             0
album_id         0
media_type_id    0
genre_id         0
composer         0
milliseconds     0
bytes            0
unit_price       0
dtype: int64

In [95]:
clean_track.to_csv('sample_data/clean-track.csv')